version: '3.8'
services:
  nginx:
    image: kim5257app/kim5257-default-nginx
    networks:
      - backbone
      - local
    volumes:
      - /home/master/nfs/kim5257-doc-nginx/conf.d:/etc/nginx/conf.d
      - /home/master/nfs/kim5257-doc-nginx/htdocs:/usr/share/nginx/html
networks:
  backbone:
    name: kim5257_gateway_backbone
    external: true
  local:
    external: false
